# Generated by Django 4.2.5 on 2023-10-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30)),
                ('resim', models.FileField(upload_to='filmler', verbose_name='Film ismi giriniz')),
            ],
        ),
    ]
