# Generated by Django 4.2.5 on 2023-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='aciklama',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
